conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  osx_arm64: default
  linux_aarch64: azure
  linux_ppc64le: azure
test: native
